### ISSUE TITLE
Ability of Local Install with NPM

### ISSUE THREAD

**Issue by cun3yt** [ncardeli/page-computed-style#2]
For portability of the code, e.g. installing on Heroku, it is better to make the code able to be installed locally. Currently if you install it locally (without npm's `-g` parameter) it fails with the error "Can't open 'serializer.js'".

To reproduce the issue:
1. Install the package locally: `npm install page-computed-style` (Make sure that it is not available globally).
1. Run `index.js` (according to the root of the project): `./node_modules/page-computed-style/index.js -p http://example.com`

**Comment by cun3yt** [comment]
@ncardeli I created a pull request for the issue: https://github.com/ncardeli/page-computed-style/pull/3

**Comment by ncardeli** [comment]
Thanks @cun3yt for your contribution
